title: Adrian Exojo
description: Pagina de Adrian Exojo.
show_downloads: true
google_analytics: 100115930
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
